
#ifndef _COMMAND_TAG_HPP_
#define _COMMAND_TAG_HPP_

enum class CommandTag {
   COMMAND_INVALID = 0,

   COMMAND_ACCEPT,
   COMMAND_ATTACK,
   COMMAND_BACK,
   COMMAND_HELP,
   COMMAND_LOAD,
   COMMAND_MOVE,
   COMMAND_QUIT,
   COMMAND_RIFT,
   COMMAND_SAVE,

   COMMAND_HEIGHT,
   COMMAND_WIDTH,
   COMMAND_OFFSET_X,
   COMMAND_OFFSET_Y
};

#endif // _COMMAND_TAG_HPP_
